import "./bootstrap";
import "vue-toastification/dist/index.css";
import "flag-icons/css/flag-icons.min.css";
import { createApp, h } from "vue";
import { createInertiaApp } from "@inertiajs/vue3";
import { ZiggyVue } from "ziggy-js";
import Toast from "vue-toastification";
import { createI18n } from "vue-i18n";
import "./echo.js";
import DashboardLayout from "./components/layout/DashboardLayout.vue";

const i18n = createI18n({
    locale: window.locale,
    fallbackLocale: "en",
    legacy: false,
    messages: {
        en: {
            create: "Create",
            delete: "Delete",
            save: "Save",
            login: "Login",
            register: "Register",
            logout: "Logout",
            username: "Username",
            password: "Password",
            submit: "Submit",
            cancel: "Cancel",
            edit: "Edit",
            update: "Update",
            deleteConfirmation: "Are you sure you want to delete?",
            noResults: "No results found",

            search: "Search",
            searchPlaceholder: "Type to search...",
            assigned: "Assigned",
            assign: "Assign",
            demo: "Demo",
            test: "Test",
            detail: "Detail",
            viewDetails: "View Details",
            back: "Back",
            next: "Next",
            previous: "Previous",
            loading: "Loading...",
            review: "Review",
            demoTest: "Demo Test",
            title: "Title",
            createdBy: "Created By",
            status: "Status",
            action: "Action",
            filter: "Filter",
            category: "Category",
            allCategories: "All Categories",
            selectCategory: "Select Category",
            categories: "Categories",
            users: "Users",
            quizzes: "Quizzes",
            dashboard: "Dashboard",
            name: "Name",
            submit: "Submit",
            choice: "Choice",
            description: "Description",
            addChoice: "Add Choice",
            addQuestion: "Add Question",
            question: "Question",
            answer: "Answer",
            registeredAt: "Registered At",
            email: "Email",
            appLogin: "App Login",
            assignedAt: "Assigned At",
            yourScore: "Your Score",
            correctAnswer: "Correct Answer",
            totalQuestions: "Total Questions",
            yourAnswer: "Your Answer",
            completedAssigns: "Completed Assigns",
            noCompletedAssigns: "No completed assignments yet",
            cancel: "Cancel",
            qrCodeOnce: "This QR code can be used only once",
            scanToLogin: "Scan to login",
            pleaseWait: "Please wait, this can take a little...",
            dataUpdated: "Data is updated",
            loginSuccess: "Login successful. Welcome back!",
            refresh: "更新",
            dataCreated: "Data is created",
            score: "Score",
            pending: "Pending",
            complete: "Complete",
            explanation: "explanation",
            draft: "Draft",
            published: "Published",
            exportResult: "Export Results",
            dataEmpty: "Data is empty",
            notifications: "Notifications",
            confirmPassword: "Confirm Password",
            confirmEmail: "Confirm Email",
            message: "message",
            Myanmar: "Myanmar",
            English: "English",
            Japanese: "Japanese",
        },
        ja: {
            message: "メッセージ",
            pending: "保留中",
            complete: "完了",
            score: "スコア",
            create: "作成",
            delete: "削除",
            save: "保存",
            login: "ログイン",
            register: "登録",
            logout: "ログアウト",
            username: "ユーザー名",
            password: "パスワード",
            submit: "送信",
            cancel: "キャンセル",
            edit: "編集",
            update: "更新",
            deleteConfirmation: "削除してもよろしいですか？",
            noResults: "結果が見つかりません",

            search: "検索",
            searchPlaceholder: "検索語を入力...",
            assigned: "割り当て済み",
            assign: "割り当てる",
            demo: "デモ",
            test: "テスト",
            detail: "詳細",
            viewDetails: "詳細を見る",
            back: "戻る",
            next: "次へ",
            previous: "前へ",
            loading: "読み込み中...",
            review: "レビュー",
            demoTest: "デモテスト",
            title: "タイトル",
            createdBy: "作成者",
            status: "ステータス",
            action: "操作",
            filter: "フィルター",
            category: "カテゴリー",
            allCategories: "すべてのカテゴリー",
            selectCategory: "カテゴリーを選択",
            categories: "カテゴリー",
            users: "ユーザー",
            quizzes: "クイズ",
            dashboard: "ダッシュボード",
            name: "名前",
            submit: "送信",
            choice: "選択",
            addChoice: "選択肢を追加",
            description: "説明",
            addQuestion: "質問を追加",
            question: "質問",
            addAnswer: "答えを追加",
            answer: "答え",
            registeredAt: "登録日",
            email: "メール",
            confirmEmail: "メール確認",
            appLogin: "アプリログイン",
            assignedAt: "割り当て日時",
            yourScore: "あなたのスコア",
            correctAnswer: "正解",
            totalQuestions: "総質問数",
            yourAnswer: "あなたの答え",
            completedAssigns: "完了した課題",
            noCompletedAssigns: "まだ完了した課題はありません",
            cancel: "キャンセル",
            qrCodeOnce: "このQRコードは一度だけ使用できます",
            scanToLogin: "スキャンしてログイン",
            pleaseWait: "しばらくお待ちください、少し時間がかかります...",
            dataUpdated: "データが更新されました",
            loginSuccess: "ログインに成功しました。お帰りなさい！",
            refresh: "更新",
            dataCreated: "データが作成されました",
            explanation: "説明 ",
            draft: "下書き",
            published: "公開",
            exportResult: "エクスポート結果",
            dataEmpty: "データがありません",
            notifications: "通知",
            confirmPassword: "パスワード確認",
            Myanmar: "ミャンマー語",
            English: "英語",
            Japanese: "日本語",
        },
        my: {
            create: "ဖန်တီးပါ",
            delete: "ဖျက်ပါ",
            save: "သိမ်းဆည်းပါ",
            login: "လော့ဂ်အင်ဝင်ပါ",
            register: "စာရင်းသွင်းပါ",
            logout: "ထွက်မည်",
            username: "အသုံးပြုသူအမည်",
            password: "စကားဝှက်",
            submit: "တင်ပြပါ",
            cancel: "ဖျက်သိမ်းပါ",
            edit: "တည်းဖြတ်ပါ",
            update: "အသစ်ပြင်ဆင်ပါ",
            deleteConfirmation: "ဖျက်မှာသေချာပြီလား?",
            noResults: "ရလဒ်မတွေ့ပါ",
            search: "ရှာဖွေပါ",
            searchPlaceholder: "ရှာဖွေရန်ရိုက်ထည့်ပါ...",
            assigned: "တာဝန်ပေးပြီး",
            assign: "တာဝန်ပေးပါ",
            demo: "အစမ်း",
            test: "စာမေးပွဲ",
            detail: "အသေးစိတ်",
            viewDetails: "အသေးစိတ်ကြည့်ရန်",
            back: "နောက်သို့",
            next: "နောက်တစ်ခု",
            previous: "ရှေ့တစ်ခု",
            loading: "ဖတ်ရှုနေသည်...",
            review: "ပြန်လည်သုံးသပ်ပါ",
            demoTest: "အစမ်းစာမေးပွဲ",
            title: "ခေါင်းစဉ်",
            createdBy: "ဖန်တီးသူ",
            status: "အခြေအနေ",
            action: "လုပ်ဆောင်ချက်",
            filter: "စစ်ထုတ်ပါ",
            category: "အမျိုးအစား",
            allCategories: "အမျိုးအစားအားလုံး",
            selectCategory: "အမျိုးအစားရွေးချယ်ပါ",
            categories: "အမျိုးအစားများ",
            users: "အသုံးပြုသူများ",
            quizzes: "မေးခွန်းများ",
            dashboard: "ဒက်ရှ်ဘုတ်",
            name: "အမည်",
            choice: "ရွေးချယ်မှု",
            description: "ဖော်ပြချက်",
            addChoice: "ရွေးချယ်မှုထည့်ပါ",
            addQuestion: "မေးခွန်းထည့်ပါ",
            question: "မေးခွန်း",
            answer: "အဖြေ",
            registeredAt: "စာရင်းသွင်းချိန်",
            email: "အီးမေးလ်",
            appLogin: "အက်ပ်ဝင်ရန်",
            assignedAt: "တာဝန်ပေးချိန်",
            yourScore: "သင့်အမှတ်",
            correctAnswer: "မှန်ကန်သောအဖြေ",
            totalQuestions: "စုစုပေါင်းမေးခွန်း",
            yourAnswer: "သင်၏အဖြေ",
            completedAssigns: "ပြီးဆုံးသောတာဝန်များ",
            noCompletedAssigns: "ပြီးဆုံးသောတာဝန်မရှိသေးပါ",
            qrCodeOnce: "ဤ QR ကုဒ်ကိုတစ်ကြိမ်သာသုံးနိုင်သည်",
            scanToLogin: "QR ကုဒ်ဖတ်ပြီးဝင်ပါ",
            pleaseWait: "ကျေးဇူးပြု၍ စောင့်ပါ၊ အချိန်အနည်းငယ်လိုအပ်နိုင်သည်...",
            dataUpdated: "ဒေတာကိုအသစ်ပြင်ဆင်ပြီးပါပြီ",
            loginSuccess: "လော့ဂ်အင်အောင်မြင်ပါသည်။ နောက်ထပ်ကြိုဆိုပါတယ်!",
            refresh: "ပြန်လည်သစ်ဆန်းပါ",
            dataCreated: "ဒေတာအသစ်ဖန်တီးပြီးပါပြီ",
            score: "အမှတ်",
            pending: "ဆိုင်းငံ့နေသည်",
            complete: "ပြီးဆုံးသည်",
            explanation: "ရှင်းပြချက်",
            draft: "မူကြမ်း",
            published: "ထုတ်ဝေပြီး",
            exportResult: "ရလဒ်တင်ပို့ရန်",
            dataEmpty: "ဒေတာမရှိပါ",
            notifications: "အသိပေးချက်များ",
            confirmPassword: "စကားဝှက်အတည်ပြုပါ",
            confirmEmail: "အီးမေးလ်အတည်ပြုပါ",
            message: "စာမျက်နှာ",
            Myanmar: "မြန်မာဘာသာ",
            English: "အင်္ဂလိပ်ဘာသာ",
            Japanese: "ဂျပန်ဘာသာ",
        },
    },
});

createInertiaApp({
    resolve: async (name) => {
        const pages = import.meta.glob("./Pages/**/*.vue", { eager: false });
        const page = await pages[`./Pages/${name}.vue`]();

        if (name.startsWith("Dashboard")) {
            page.default.layout ??= DashboardLayout;
        }

        return page.default;
    },
    setup({ el, App, props, plugin }) {
        createApp({ render: () => h(App, props) })
            .use(plugin)
            .use(ZiggyVue)
            .use(Toast)
            .use(i18n)
            .mount(el);
    },
}).then(() => {
    document.getElementById("app").removeAttribute("data-page");
});
