name: App Testing

on:
  push:
    branches:
    - main
  pull_request:
  schedule:
  - cron: '0 0 * * *'

jobs:
  test:

    strategy:
      matrix:
        operating-system:
        - ubuntu-latest
        php-version:
        - '8.4'

    name: PHP ${{ matrix.php-version }} on ${{ matrix.operating-system }}

    runs-on: ${{ matrix.operating-system }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: bcmath, ctype, exif, fileinfo, gd, json, mbstring, openssl, pdo, tokenizer, xml
        coverage: none

    - name: Prepare the environment
      run: cp .env.example .env

    - name: Get composer cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Setup composer cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install composer dependencies
      env:
        COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Install node dependencies
      run: npm ci

    - name: Migrate test DB
      run: php artisan migrate

    - name: Generate application key
      run: php artisan key:generate

    - name: Build assets
      run: npm run build

    - name: Run tests
      run: php artisan test

    - name: Show README.md in job summary
      if: success()
      run: |
        echo "## 📘 README.md" >> $GITHUB_STEP_SUMMARY
        echo '```markdown' >> $GITHUB_STEP_SUMMARY
        cat README.md >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
